# Generated by Django 4.0.5 on 2022-06-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='core',
            name='auto_click_power',
        ),
        migrations.RemoveField(
            model_name='core',
            name='level',
        ),
    ]
