# Generated by Django 4.0.5 on 2022-06-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_core_auto_click_power_core_level_boost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='core',
            name='auto_click_power',
        ),
        migrations.RemoveField(
            model_name='core',
            name='level',
        ),
        migrations.DeleteModel(
            name='Boost',
        ),
    ]
