# Generated by Django 4.0.5 on 2022-06-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_boost_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boost',
            name='type',
        ),
        migrations.RemoveField(
            model_name='core',
            name='auto_click_power',
        ),
        migrations.AlterField(
            model_name='boost',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
